name: Deploy preview
description: On push on test branch, deploy preview to Coolify.

on:
    workflow_dispatch:
    # push:
    #     branches: [test]

jobs:
    deploy:
        name: Deploy to Coolify
        runs-on: ubuntu-latest
        steps:
          - name: Trigger Coolify Deploy
            run: |
              curl -X GET "${{ secrets.COOLIFY_API_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_ECO_SERVICE_PREVIEW_UUID }}&force=false&branch=test" \
                -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"
